### ISSUE TITLE
网易云似乎更新了api，不知道这个榜单数据是不是很准确啊？

### ISSUE THREAD

**Issue by liguge** [zsw12013/neteaseMusicCrawler#1]
https://github.com/pengshiqi/NetEaseMusicCrawl

**Comment by zsw12013** [comment]
是嘛，要是更新了那就不准确了

**Comment by liguge** [comment]
@zsw12013  比如,就没有~   **something just like this**

**Comment by liguge** [comment]
@zsw12013 有没有时间修改一下啊~这是一个找歌的好东西，~

**Comment by zsw12013** [comment]
@liguge 最近没有。。。刚入职到一个小公司，非常忙，估计没时间搞

**Comment by liguge** [comment]
感觉2017年上榜的歌曲都没有统计~ @zsw12013
